server:
  port: 8199
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka/
spring:
  application:
    name: cms-zuul
zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: cms-user-consumer
    api-b:
      path: /product/**
      serviceId: cms-product-consumer

