server:
  port: 8184

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka
spring:
  application:
    name: cms-product-consumer
  rabbitmq:
    host: 192.168.1.145
    port: 5672
    username: rbdq
    password: 123456

  main:
    allow-bean-definition-overriding: true #允许相同key情况下beanDefinition实例的覆盖
  thymeleaf:
    cache: false
    enabled: true

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000
