server:
  port: 8182

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka
spring:
  application:
    name: cms-user-consumer
  data:
    mongodb:
      port: 27017
      host: localhost
      database: 1810a

  main:
    allow-bean-definition-overriding: true #允许相同key情况下beanDefinition实例的覆盖
  thymeleaf:
    cache: false
    enabled: true

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000